tap 'homebrew/bundle'
#tap 'homebrew/fuse'
tap 'caskroom/cask'
tap 'caskroom/drivers'
tap 'caskroom/fonts'
tap 'caskroom/versions'

tap 'AdoptOpenJDK/openjdk'

brew 'bash'
brew 'bash-completion'
brew 'tree'
brew 'grep'

brew 'autoconf'
brew 'automake'
brew 'libtool'
brew 'gnu-getopt'
brew 'shellcheck'

brew 'circleci'

brew 'openssl'
brew 'gpg'
brew 'https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb'
brew 'libjwt'

cask 'keybase'

brew 'wget'
brew 'markdown'

cask 'google-chrome'
cask 'brave'
cask 'tor-browser'

brew 'awscli'
cask 'google-cloud-sdk'
brew 'rpm'
brew 'git'
brew 'hub'
brew 'git-flow-avh'
brew 'git-subrepo'
brew 'subversion'
brew 'mercurial'

cask 'sourcetree'

brew 'maven'
brew 'ant'
brew 'sbt'
brew 'gradle'

brew 'ruby'
brew 'python'
brew 'scala'
brew 'go'
brew 'rust'
brew 'groovy'
brew 'jvmtop'

cask 'java'
cask 'java8'
cask 'java'
cask 'adoptopenjdk'
cask 'adoptopenjdk8'
cask 'adoptopenjdk10'
cask 'adoptopenjdk11'
brew 'docker-completion'
brew 'docker'
brew 'kubectl'
brew 'kubernetes-helm'
cask 'minikube'
brew 'cassandra'
brew 'hadoop'
brew 'hbase'
brew 'zookeeper'
brew 'apache-spark'
brew 'mysql'
brew 'titan-server'
cask 'pycharm-ce'
cask 'intellij-idea-ce'
cask 'visualvm'
cask 'rubymine'
cask 'atom'
brew 'packer'
brew 'consul'
brew 'terraform'
brew 'nomad'
brew 'serf'
brew 'vault'
brew 'ansible'
brew 'nmap'
brew 'graphviz'
brew 'neo4j'
cask 'vagrant'
cask 'vagrant-manager'
cask 'slack'
cask 'skype'
cask 'limechat'
cask 'hipchat'
brew 'jq'
brew 'watch'
cask 'coolterm'
cask 'tunnelblick'
cask 'tftpserver'
cask 'xquartz'

brew 'gnu-sed', args: ['with-default-names']
brew 'unzip', args: ['with-default-names']

cask 'ticktick'
cask 'the-unarchiver'
cask 'etcher'

brew 'coreutils'
brew 'binutils'
brew 'inetutils'
brew 'arp-scan'
brew 'iproute2mac'
brew 'expect'
brew 'tmux-xpanes'
brew 'pidof'
brew 'homebrew/cask/visual-studio-code'

cask 'keybase'
