tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'jenkins-x/jx'
tap 'AdoptOpenJDK/openjdk'
tap 'boz/repo'
tap 'weaveworks/tap'

brew 'bash'
brew 'zsh'
brew 'bash-completion'
brew 'tree'
brew 'grep'
brew 'certbot'

brew 'coreutils'
brew 'findutils'
brew 'gnu-tar'
brew 'gnu-sed'
brew 'gawk'
brew 'gnutls'
brew 'gnu-indent'
brew 'gnu-getopt'
brew 'grep'

brew 'findutils'
brew 'gnu-indent'
brew 'gnu-sed'
brew 'gnutls'
brew 'grep'
brew 'gnu-tar'
brew 'gawk'

brew 'autoconf'
brew 'automake'
brew 'libtool'
brew 'gnu-getopt'
brew 'shellcheck'

brew 'circleci'
brew 'npm'
#brew 'nvm'
brew 'openssl'
brew 'gpg'
#brew 'https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb'
#brew install 'https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb'

brew 'libjwt'

cask 'keybase'

brew 'wget'
brew 'markdown'

cask 'google-chrome'
cask 'brave-browser'
cask 'tor-browser'
cask 'insomnia'
cask '1password'

brew 'awscli'
brew 'aws-iam-authenticator'
brew 'awslogs'
cask 'google-cloud-sdk'
brew 'rpm'
brew 'git'
brew 'hub'
brew 'git-flow-avh'
brew 'git-subrepo'
brew 'pre-commit'
cask 'fork'

cask 'sourcetree'

brew 'maven'
brew 'yarn'
brew 'nvm'
brew 'ant'
brew 'sbt'
brew 'gradle'
brew 'jx'
brew 'hyperkit'

brew 'ruby'
brew 'python'
brew 'scala'
brew 'go'
brew 'dep'
brew 'rust'
brew 'groovy'
brew 'jvmtop'

cask 'java'
cask 'java8'
cask 'java'
cask 'adoptopenjdk'
cask 'adoptopenjdk8'
cask 'adoptopenjdk10'
cask 'adoptopenjdk11'
cask 'adoptopenjdk12'
brew 'bazel'
brew 'docker-completion'
brew 'docker-machine-driver-hyperkit'
brew 'docker'
brew 'kubectl'
brew 'txn2/tap/kubefwd'
brew 'weaveworks/tap/eksctl'
#brew 'helm'
brew 'helm@2'
brew 'sops'
cask 'minikube'
brew 'derailed/k9s/k9s'
brew 'derailed/popeye/popeye'
brew 'kubectx'
brew 'kube-ps1'
brew 'stern'
tap farmotive/k8s
brew 'kpoof'
brew 'boz/repo/kail'
brew 'cassandra'
brew 'hadoop'
brew 'hbase'
brew 'zookeeper'
brew 'apache-spark'
brew 'mysql'
brew 'postgresql'
brew 'pgcli'
cask 'pgadmin4'
brew 'postgis'
brew 'redis'
cask 'pycharm-ce'
cask 'intellij-idea-ce'
cask 'visualvm'
cask 'rubymine'
cask 'atom'
brew 'packer'
brew 'consul'
brew 'terraform'
brew 'nomad'
brew 'serf'
brew 'vault'
brew 'ansible'
brew 'nmap'
brew 'graphviz'
brew 'neo4j'
cask 'slack'
cask 'skype'
brew 'jq'
brew 'yq'
brew 'watch'
cask 'coolterm'
cask 'tunnelblick'
cask 'tftpserver'

brew 'gnu-sed' #, args: ['with-default-names']
brew 'unzip' #, args: ['with-default-names']

cask 'the-unarchiver'
cask 'etcher'

brew 'coreutils'
brew 'binutils'
brew 'inetutils'
brew 'arp-scan'
brew 'iproute2mac'
brew 'expect'
brew 'tmux'
brew 'tmux-xpanes'
brew 'tmate'
brew 'pidof'

cask 'visual-studio-code'

brew 'mas'
